services:

  user-service:
    build: .
    container_name: user-service

    ports:
      - "8081:8081"

    restart: always

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.2.4:5432/myappdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass1234
