spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
