name: cIPipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (optional now, can even remove)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Docker image (includes Maven inside container)
        run: docker build -t user-service:latest .

      - name: Start containers
        run: |
          docker-compose down
          docker-compose up -d
          sleep 20

      - name: Check service is running
        run: curl -f http://localhost:8081/api/test/all || exit 1

      - name: Show logs
        run: docker-compose logs
